"""Add changes_requested field to metrics table

Revision ID: 260408174153
Revises: 240408013000
Create Date: 2026-04-08 17:41:53.843782

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '260408174153'
down_revision = '240408013000'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('changes_requested', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metrics', 'changes_requested')
    # ### end Alembic commands ###
